// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGfegJpIEJK5NAp9AJ_Kve9QROfyL4_10',
    appId: '1:258492871250:web:a627337c0c92d05914258b',
    messagingSenderId: '258492871250',
    projectId: 'flemingcore-53272',
    authDomain: 'flemingcore-53272.firebaseapp.com',
    databaseURL: 'https://flemingcore-53272-default-rtdb.firebaseio.com',
    storageBucket: 'flemingcore-53272.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLNacAmTqS-AROGo7MXM4XNtDvJPqdfk8',
    appId: '1:258492871250:android:2f96026b20459beb14258b',
    messagingSenderId: '258492871250',
    projectId: 'flemingcore-53272',
    databaseURL: 'https://flemingcore-53272-default-rtdb.firebaseio.com',
    storageBucket: 'flemingcore-53272.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuI0QuIHTtvhPnVMXrrZ3cBDM12LfjRzY',
    appId: '1:258492871250:ios:e992f8ef6ea172a114258b',
    messagingSenderId: '258492871250',
    projectId: 'flemingcore-53272',
    databaseURL: 'https://flemingcore-53272-default-rtdb.firebaseio.com',
    storageBucket: 'flemingcore-53272.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGfegJpIEJK5NAp9AJ_Kve9QROfyL4_10',
    appId: '1:258492871250:web:fdc0fb5ce33024e914258b',
    messagingSenderId: '258492871250',
    projectId: 'flemingcore-53272',
    authDomain: 'flemingcore-53272.firebaseapp.com',
    databaseURL: 'https://flemingcore-53272-default-rtdb.firebaseio.com',
    storageBucket: 'flemingcore-53272.firebasestorage.app',
  );
}
